version: "3.6"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations library
            python manage.py migrate
            python manage.py createtestuser
            python manage.py loaddata library/fixtures/books.json
            python manage.py loaddata library/fixtures/clients.json
            python manage.py loaddata library/fixtures/rents.json
            python manage.py test
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    
    environment:
      - DB_HOST=DB
      - DB_NAME=agriness_db
      - DB_USER=agriness
      - DB_PASS=4gr1n3ss

    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=agriness
      - POSTGRES_PASSWORD=4gr1n3ss
      - POSTGRES_DB=agriness_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
